### ISSUE TITLE
missing hardware diagram

### ISSUE THREAD

**Issue by evanleeturner** [bablokb/pi-wake-on-rtc#1]
Your hardware diagram is missing on the readme file:  https://github.com/bablokb/pi-wake-on-rtc/blob/master/doc/circuit.md

I would like to build this, but without the diagram that may be hard :)

**Comment by bablokb** [comment]
Oops. You are right, this is missing. Give me some time, I will add it.

**Comment by bablokb** [comment]
Added the document (it mainly links to files already available in the pcb-directory). If you have additional questions, just let me know. I'm the software-guy in this project, but will forward any hardware-related questions to the hardware-guru.

**Comment by evanleeturner** [comment]
thanks :)  I'm going to try to put this together sometime soon.  I probably have all of the parts... the part list is in German though...

**Comment by bablokb** [comment]
If you are unsure, just ask and I will do my best to translate (but I'm not sure if I know all the special English vocabulary).
