### ISSUE TITLE
Raspberry Pi5

### ISSUE THREAD

**Issue by Bra1nsen** [bablokb/pi-wake-on-rtc#3]
How is it working for Pi5?

**Comment by bablokb** [comment]
You don't need this project for a Pi5. The Pi5 has an internal RTC that will happily wake up the Pi5.

You can set the wakeup time with (execute as root):

    date -d "+10 minutes" +'%s' > /sys/class/rtc/rtc0/wakealarm

The `date` command is very powerful, see the man-pages. You can pass relative times as in my example above, or absolute dates. Some more examples:

    date -d tomorrow  +'%s' > /sys/class/rtc/rtc0/wakealarm
    date -d "tomorrow 08:00" +'%s' > /sys/class/rtc/rtc0/wakealarm
    date -d "next monday 08:00" +'%s' > /sys/class/rtc/rtc0/wakealarm
    date -d "+5 minutes" +'%s' > /sys/class/rtc/rtc0/wakealarm
    date -d "+5 hours" +'%s' > /sys/class/rtc/rtc0/wakealarm
    date -d "22:30 2024-10-21" +'%s' > /sys/class/rtc/rtc0/wakealarm

**Comment by Bra1nsen** [comment]
Thanks just tested it, and it worked. But its still consuming 1.9 Watts in Sleep Mode. Any Idea?

![image](https://github.com/bablokb/pi-wake-on-rtc/assets/58213050/8771bbfd-bf74-4f86-8996-e2bca46d347b)

**Comment by bablokb** [comment]
Yes, you have to update your EEPROM-settings. You should add:

    POWER_OFF_ON_HALT=1

Edit with:

    sudo rpi-eeprom-config --edit

and reboot afterwards.
